helm-charts/datacater/templates/postgres.yaml
helm-charts/datacater/templates/statefulset.yaml
k8s-manifests/minikube-with-postgres-ns-default.yaml

Removing storage class from helm template
for postgres. This lets the underlying
distro use the actual default.

fix(chart): remove SC from template

---

ui/src/components/pipelines/PipelineDesigner.js
ui/src/components/pipelines/pipeline_designer/Grid.js
ui/src/components/pipelines/pipeline_designer/context_bar/filter/Attribute.js
ui/src/components/pipelines/pipeline_designer/context_bar/filter/AttributeFilterList.js
ui/src/components/pipelines/pipeline_designer/context_bar/filter/Edit.js
ui/src/components/pipelines/pipeline_designer/context_bar/transformation/Attribute.js
ui/src/components/pipelines/pipeline_designer/context_bar/transformation/AttributeTransformationList.js
ui/src/components/pipelines/pipeline_designer/context_bar/transformation/Config.js
ui/src/components/pipelines/pipeline_designer/context_bar/transformation/Edit.js
ui/src/components/pipelines/pipeline_designer/grid/DataTypeIcon.js
ui/src/components/pipelines/pipeline_designer/grid/TableHeaderCell.js
ui/src/scss/context-bar.scss

When adding a transform or filter to a field in the UI, warn the user if the filter or transform expects another data type than the one of the field.
Example:

feat(ui): Warn about data type mismatches

---

CONTRIBUTING.md
licenses/platform-api/third_party.md
licenses/serde/third_party.md
pipeline/build.gradle
pipeline/src/main/docker/Dockerfile.jvm
pipeline/src/main/docker/Dockerfile.legacy-jar
pipeline/src/main/docker/Dockerfile.native
pipeline/src/main/docker/Dockerfile.native-micro
pipeline/src/main/java/io/datacater/Pipeline.java
pipeline/src/main/java/io/datacater/PipelineConfig.java
pipeline/src/main/java/io/datacater/exceptions/Error.java
pipeline/src/main/java/io/datacater/exceptions/TransformationException.java
pipeline/src/main/resources/application.yml
pipeline/src/main/resources/sample-.testcontainers.properties
pipeline/src/test/java/io/datacater/PipelineTest.java
platform-api/src/main/resources/application.yml
python-runner/README.md
python-runner/runner.py
settings.gradle

This PR is for the implementation of the Datacater Pipeline Concept.
- Messages are to be consumed from the definded stream-in
- Forwarded to a Datacater Python-runner
* Here, it is processed (transformed and or filtered)
- The processed message is produced to the defined stream-out
The defined test will currently not work, as there is a bug in the currently deployed python-runner on the `/batch` endpoint. I fixed the endpoint in the PR. 
To test manually, the python runner and be run locally:
1. `pip3 install -r requirements.txt`
2. `python3 -m uvicorn runner:app`
And by then setting environment variables:
- `DATACATER_PYTHONRUNNER_PORT=8000`
- `DATACATER_PYTHONRUNNER_HOST=localhost`

Feat(pipeline): create initial pipeline implementation

---

helm-charts/datacater/Chart.yaml
helm-charts/datacater/templates/statefulset.yaml
helm-charts/datacater/templates/ui.yaml
helm-charts/datacater/values.yaml
k8s-manifests/minikube-with-postgres-ns-default.yaml

Update the Helm chart and Kubernetes manifest to be compatible with the most recent version of our application:
* Update all images to most recent release, i.e., `alpha-20221109-1`
* Add prefix to `DATACATER_FILTERS_PATH` and `DATACATER_TRANSFORMS_PATH`
* Add prefix to paths of liveness and readiness probes

feat(helm): Ensure compatibility with latest app version

---

ui/src/containers/pipelines/EditPipeline.js

Avoid calling the `/pipelines/preview` endpoint when only inspecting the source stream.

feat(ui): Do not preview pipeline when inspecting source stream

---

ui/src/components/pipelines/pipeline_designer/context_bar/FilterConfig.js
ui/src/components/pipelines/pipeline_designer/context_bar/TransformConfig.js

Let the user know if a filter or transform does not require any configuration instead of keeping the "Config" tab in the sidebar empty.
Before:
After:

feat(ui): Note if a filter or transform does not require any config

---

ui/src/containers/pipelines/EditPipeline.js

When removing a transform in the UI-based pipeline designer, we previously set the transform key to an empty string, which produced pipeline YAMLs like the following one:
```yaml
spec:
steps:
fields:
email:
transform:
key: "hash"
name:
transform:
key: ""
```
These pipeline YAMLs failed when being evaluated with the Python runner since the runner could not find a transform with an empty key.
This commity changes this behavior and lets the pipeline designer correctly remove the transforms from the YAML, producing pipeline YAML that can be processed by the Python runner, e.g.:
```yaml
spec:
steps:
fields:
email:
transform:
key: "hash"
```

fix(ui): Correctly reset transforms

---

ui/src/components/pipelines/pipeline_designer/Grid.js

Fix the height of the table header for pipeline steps of kind "Field".
Before:
After:

fix(ui): Fix header height of table

---

platform-api/src/main/java/io/datacater/core/deployment/K8Deployment.java
platform-api/src/main/java/io/datacater/core/deployment/StaticConfig.java
ui/src/helpers/getStreamConnectionOptions.js

This PR adds a consumer `group.id` to our pipelines `stream-in` when creating a deployment.
The `group.id` is the uuid of the deployment.
If users add a `group-id` to the stream-config, it will be overwritten by us.

feat(deployment): add consumer group to stream-in

---

ui/src/components/pipelines/PipelineDesigner.js
ui/src/components/pipelines/pipeline_designer/Grid.js
ui/src/components/pipelines/pipeline_designer/grid/DebugView.js
ui/src/components/pipelines/pipeline_designer/grid/TableHeaderCell.js
ui/src/containers/pipelines/EditPipeline.js
ui/src/helpers/profileRecords.js
ui/src/scss/grid.scss

This PR extends our UI-based pipeline designer with debugging capabilities.
When applying a transform to a record fails, our Python runner extends the `metadata` field of the record with an `error` object. We now read this field and visually highlight the record in the UI with a red background color:
Users can click the affected record to open a "debug view", which provides access to the description of the error including a stacktrace, to the original record, and the configuration of the transform that failed:
Please consider this PR as a discussion. I am not yet 100% happy with the implementation.
I would appreciate it if you could check out the PR branch locally and play with the debug view. Please let me know what you think about it and whether this debug view helps you debugging …

feat(ui): Allow debugging of failed transforms

---

ui/src/containers/streams/EditStream.js
ui/src/containers/streams/NewStream.js

Show a warning if a stream defined the consumer property `group.id` because DataCater automatically overwrites it when starting a Deployment.
Fixes #64

feat(ui/streams): Show a warning if `group.id` is set

---

platform-api/src/main/resources/application.yml
ui/src/helpers/getApiPathPrefix.js

This updates our API prefix from `/api/alpha` to `/api/v1`.
Once we have built the first release after merging this PR, we need to update the paths in [our documentation](https://docs.datacater.io/introduction/welcome) and [Kubernetes health probes](https://github.com/DataCater/datacater/blob/main/k8s-manifests/minikube-with-postgres-ns-default.yaml).

feat(api): Update version to v1

---

platform-api/src/main/java/io/datacater/core/deployment/DeploymentEndpoint.java

Allow to delete a DataCater deployment even if the underlying Kubernetes Deployment does not exist in the Kubernetes cluster.
This can be the case if a Kubernetes administrator has deleted the resource directly in Kubernetes, bypassing the DataCater API.
Fixes #74

feat(deployments): Allow deletion of deployments if no K8 object exists

---

pipeline/src/main/java/io/datacater/Pipeline.java
pipeline/src/main/java/io/datacater/PipelineConfig.java

When the processing of a record fails, log the following information:
* key of the record
* value of the record
* metadata of the record (e.g., offset)
* detailed information on the error (e.g., exception name, exception message, stacktrace, etc.)
Fixes #61

feat(pipeline): Improve error logging

---

ui/package-lock.json
ui/package.json
ui/src/components/pipelines/pipeline_designer/context_bar/CodeEditor.js
ui/src/containers/deployments/ListDeployments.js
ui/src/containers/pipelines/ListPipelines.js
ui/src/containers/streams/ListStreams.js
ui/src/scss/grid.scss

In the UI, sort resources by their `updatedAt`field, showing the most recently updated resources first in the list.
This helps users to navigate their resources in a more transparent way, since names and UUIDs are sometimes not enough for differentiating different resources.
We now also show the update time in the UI:

feat(ui): Sort resources by their update time

---

ui/src/containers/pipelines/EditPipeline.js

When resetting a transform or filter, close the sidebar correctly and do not leave an empty area.
The _empty area_ is clearly visible on the following screenshot:

fix(ui): Close sidebar correctly when resetting transform

---

pipeline/src/main/java/io/datacater/KafkaConfig.java
pipeline/src/main/java/io/datacater/Pipeline.java
pipeline/src/main/java/io/datacater/PipelineConfig.java
pipeline/src/main/resources/application.yml
pipeline/src/test/java/io/datacater/PipelineTest.java
platform-api/src/main/java/io/datacater/core/deployment/K8Deployment.java
platform-api/src/main/java/io/datacater/core/deployment/StaticConfig.java

We cannot use Smallrye's kafka-configuration option for passing channel configs to pipelines that are running in the native mode.
To support native mode, this PR introduces the usage of environment variables for configuring streams/channels of the pipeline.

Pass stream configs as environment variables to pipelines

---

ui/src/containers/pipelines/EditPipeline.js
ui/src/containers/streams/InspectStream.js
ui/src/helpers/profileRecords.js

We automatically profile the schema of records by inspecting the results of the pipeline preview.
If pipeline drops fields or entire records, we previously have not been able to render fields that defined a transform or filter, making it hard to users to revert them.
With this fix, we automatically add fields, which define a transform or filter, to the profiled schema of the records, enabling users to always change any part of the pipeline, regardless of whether the preview returns records or not.
Before this fix, the grid would stay completely empty and uneditable, if all records have been filtered out:
With this fix, we still show the field that applies the filter, allowing users to potentially remove the filter again:

fix(ui): Always show fields that are transformed

---

ui/src/components/pipelines/PipelineDesigner.js
ui/src/components/pipelines/pipeline_designer/grid/TableHeaderCell.js
ui/src/components/pipelines/pipeline_designer/grid/Toolbar.js

If a pipeline step only defines a filter but no transform, highlight its name in the grid view.
This helps users to quickly navigate pipelines.
Before:
After:

fix(ui): Highlight filters

---

ui/src/components/pipelines/PipelineDesigner.js
ui/src/components/pipelines/pipeline_designer/grid/Toolbar.js
ui/src/containers/pipelines/EditPipeline.js

Allow users to change the size of the sample set in the pipeline designer, which is set to 100 by default.
Use a similar approach as used for the inspection of streams:

feat(ui/pipeline-designer): Allow changing sample size

---

platform-api/src/main/java/io/datacater/core/stream/StreamsUtilities.java

The `/streams/:uuid/inspect` endpoint allows to provide the parameter `limit`, which defines the number of to-be-retrieved records.
Internally, the endpoint is using Kafka's Consumer API for retrieving the records. Thus, the number of retrieved records is additionally limited by the consumer property `max.poll.records`.
Unless the stream spec overwrites this property, `max.poll.records` defaults to `500`.
To enable users to provide any value for the `limit` parameter, we now overwrite `max.poll.records` when retrieving records and set it to `value`.

fix(streams/inspect): Overwrite `max.poll.records`

---

pipeline/src/main/java/io/datacater/KafkaConfig.java
pipeline/src/main/java/io/datacater/Pipeline.java
platform-api/src/main/java/io/datacater/core/deployment/K8Deployment.java
platform-api/src/main/java/io/datacater/core/deployment/StaticConfig.java

Pass the consumer/producer config to the SerDe classes, such that they are correctly configured.
This is needed for SerDe implementations with a configuration, e.g., AVRO.

fix(pipeline): Configure SerDe

---

ui/src/containers/pipelines/PipelineSettings.js

In some cases, the Settings page of a pipeline in the UI does not show the streams of the pipeline as selected. This happens when the pipeline object has been loaded before the stream objects.
This commit fixes this issue by enforcing that streams are retrieved from the backend before the pipeline.
It looks as follows when this bug occurs:
It should however look as follows:

fix(ui/pipeline): Load streams before pipeline

---

platform-api/src/main/resources/application.yml

This PR is to remove our versioned path prefix from non-application resources that are not managed by us (`/health`, `/metrics`, etc.)

feat(api-path): remove root-path from non-app routes

---

ui/src/containers/streams/InspectStream.js

When inspecting a stream in the UI, update the limit parameter on blur and not on change, to provide a more convenient way for entering multi-digit numbers.
Fixes #106

feat(ui/streams): Update limit on blur

---

python-runner/runner.py
python-runner/test_runner.py
ui/src/components/pipelines/pipeline_designer/Grid.js

Let the `/preview` endpoint return which records have been changed by a pipeline:
* Each record's `metadata` now feature a new field `lastChange`
* The metadata field `lastChange` holds two keys, `key` and `value`
* If the record key holds JSON data, the object `record.metadata.lastChange.key` features an entry for each changed field of the JSON object, indicating the last step that has changed the field
* If the record value holds JSON data, the object `record.metadata.lastChange.value` features an entry for each changed field of the JSON object, indicating the last step that has changed the field
Example record:
```json
{
"key": null,
"value": {
"name": "DataCater GmbH",
"website": "https://datacater.io"
}
}
```
If the previewed pipeline modifies the value's field `name` in the third …

When previewing a pipeline in the UI, visualize changed records

---

ui/src/components/pipelines/pipeline_designer/context_bar/FilterConfig.js
ui/src/components/pipelines/pipeline_designer/context_bar/TransformConfig.js

In the UI, we warn the user if the inferred data type does not match the data type expected by a filter or transform.
If we cannot infer the data type from the sample data, we should not show a warning and confuse the user.

feat(pipeline-designer): Do not show type warnings if type is unknown

---

ui/src/components/pipelines/pipeline_designer/context_bar/DebugView.js
ui/src/components/pipelines/pipeline_designer/context_bar/FilterConfig.js
ui/src/components/pipelines/pipeline_designer/context_bar/TransformConfig.js
ui/src/containers/deployments/ShowDeployment.js
ui/src/containers/pipelines/ShowPipeline.js
ui/src/containers/streams/ShowStream.js
ui/src/helpers/jsonToYaml.js

By default, `js-yaml` breaks lines after 80 characters.
I removed the limitation, so we do not break lines after a specific length, which could become problematic when, for instance, breaking inlined Python functions that contain comments into multiple lines.
Example:
I moved the YAML formatting to a central helper function so we do not have to maintain configuration at multiple locations.

chore(ui): Remove the max line width from the YAML formatter

---

python-runner/runner.py
python-runner/test_runner.py
ui/src/components/pipelines/PipelineDesigner.js
ui/src/components/pipelines/pipeline_designer/Grid.js
ui/src/components/pipelines/pipeline_designer/context_bar/PreviewSettings.js
ui/src/components/pipelines/pipeline_designer/grid/Toolbar.js
ui/src/containers/pipelines/EditPipeline.js
ui/src/helpers/profileRecords.js
ui/src/reducers/deployments.js
ui/src/scss/grid.scss

Introduce a new preview setting that allows users to enable previewing filtered-out records.
The default behavior of the pipeline designer remains the same. It does not show filtered-out records:
If the user has enabled showing filtered-out records in the preview settings, we will show them with a gray background:
Note that we show filtered-out records only at the step that filters out the records. At successive steps, we will not show them in the UI to avoid confusing the user.

Optionally preview filtered out records

---

ui/src/containers/pipelines/EditPipeline.js

As suggested in our UI/UX session on Wednesday, this PR moves the sync status to the left side of the header, closer to the name of the pipeline:

feat(ui): Move sync status to the left side of the header

---

k8s-manifests/README_RedPanda.md
k8s-manifests/minikube-any-namespace.yaml
k8s-manifests/minikube-with-postgres-and-redpanda.yaml
k8s-manifests/minikube-with-postgres-ns-default.yaml

Added a manifest which also deploys a redpanda broker.
To access the broker inside datacater, `bootsrap.servers` is `redpanda-0.redpanda.default.svc.cluster.local.:9093`
To produce data to broker, use the following command: 
`kubectl exec -it -n default redpanda-0 -- rpk topic produce topicName --brokers='redpanda-0.redpanda.default.svc.cluster.local.:9093'`
Currently running minikube with:
- cpus: 4
- memory: 8192
By editing `/etc/hosts/` and adding the line `127.0.0.1 redpanda-0.redpanda.default.svc.cluster.local.`, you can then portforward `kubectl port-forward redpanda-0 9093:9093` and access the topics through `localhost`. This is much faster to produce test records, than using rpk inside the cluster

Feat(k8-manifest): introduce a manifest containing a redpanda broker

---

ui/src/helpers/profileRecords.js

When profiling the sample records in the frontend, we should ignore records with a `null` value to fix the following error:
```
Uncaught TypeError: can't convert null to object
profileRecords profileRecords.js:74
profileRecords profileRecords.js:58
render InspectStream.js:216

fix(ui): Ignore records with null values when profiling sample data

---

python-runner/runner.py
python-runner/test_runner.py

Fix previewing of records with null keys or values in the Python Runner.
When determining whether a pipeline has changed the key or value of a record, let's always assume a change if the key or value has been null before applying the pipeline but is not null after applying the pipeline.
We have to make this assumption since we cannot compare the keys of two dictionaries (old state and new state) given that the old state has not been a dictionary but `null`.
I also applied the `black` code formatter to the `/python-runner` folder. We should make this part of our CI pipeline so we do not forget it again in the future.

Fix previewing records with null keys or values

---

ui/src/containers/streams/InspectStream.js

For the grid view, we use a JavaScript library that requires the row property `id` filled with an unique identifier.
When inspecting a stream that featured a field with the name `id`, we have accidentally overwritten this field with the row id from the JavaScript grid.
This commit fixes this issue such that we no longer overwrite field values of sample records.
Before this fix:
After this fix:

fix(ui/streams): Do not overwrite field `id`

---

helm-charts/datacater/templates/postgres.yaml
helm-charts/datacater/values.yaml
k8s-manifests/minikube-any-namespace.yaml
k8s-manifests/minikube-with-postgres-ns-default.yaml

The directory for `PGDATA` has to be a sub-directory of the mount path.
Refs:
- https://hub.docker.com/_/postgres

fix: reference mount path to pg

---

ui/src/components/pipelines/pipeline_designer/Grid.js
ui/src/containers/streams/InspectStream.js

Fix the previewing of tombstone records, i.e., records whose value is `null`, by rendering all fields as `null` in the grid.

fix(ui): Fix previewing tombstone records

---

gradle.properties
platform-api/src/main/java/io/datacater/core/stream/KafkaStreamsAdmin.java
platform-api/src/main/java/io/datacater/core/stream/SampleMethod.java
platform-api/src/main/java/io/datacater/core/stream/StreamEndpoint.java
platform-api/src/main/java/io/datacater/core/stream/StreamService.java
platform-api/src/main/java/io/datacater/core/stream/StreamsUtilities.java
platform-api/src/main/resources/application.yml
platform-api/src/test/java/io/datacater/core/stream/StreamInspectLongTest.java
platform-api/src/test/java/io/datacater/core/stream/StreamInspectMethodsTest.java
platform-api/src/test/java/io/datacater/core/stream/StreamInspectStringTest.java
platform-api/src/test/resources/streamTestFiles/stream-test-inspect-methods.json

This PR adds a new method to retrieve messages from partitions:
The new method will first get messages from partition1, if the expected amount is not yet reached, the amount is filled with messages from aprtition 2 and so on

fix(stream-inspect): change message retrieval method

---

platform-api/src/main/resources/application.yml

We recently migrated from Quarkus 2.12 to Quarkus 2.16. [From 2.15 on](https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.15#cors-filter-returns-http-403-for-failed-preflight-requests), Quarkus started returning the HTTP response status `403` if the CORS preflight request failed. As a consequence, our authentication fails if the CORS domains are not correctly configured.
Since our open core is not addressing production use cases, we now start with disabling CORS by default to allow developers exploring DataCater without having to configure CORS domains.
Users can re-enable CORS by setting the environment variable `QUARKUS_HTTP_CORS` of the `datacater` pod(s) to `true`.

feat(platform-api): Disable CORS by default

---

k8s-manifests/README.md

Fix a few typos and improve the wording of the readme in the `/k8s-manifests` folder.

chore(k8s/readme): Fix typos and improve wording

---

ui/package-lock.json

Update the dependency `npm` to the latest patch release. This updates its indirect dependency `http-cache-semantics` and fixes a [vulnerability detected by dependabot](https://github.com/DataCater/datacater/security/dependabot/12).

feat(ui): Update npm

---

README.md

We recently changed our Helm Chart and switched from deploying our UI as a Pod to running it as a Deployment.
We added the service `datacater-ui`, which exposes the port `80` and allows to address the deployment of the UI.
This commits updates our readme accordingly.

feat(README): Reflect new service in port-forward

---

ui/src/containers/streams/InspectStream.js

In the UI, communicate error messages of a failed stream inspection to increase transparency and help users with debugging.
Fixes #162

feat(ui/streams): Show errors when inspecting streams

---

ui/src/containers/streams/EditStream.js

In the UI, disable config fields of streams that do not allow updates.
Fixes #159

feat(ui/streams): Disable fields that cannot be updated

---

.gitignore
load-image-k8s.bash

The current `load-image-k8s.bash` updates the `k8s-manifests/minikube-with-postgres-ns-default.yaml` but actually overwrites/removes the postgres `statefulset` and `service`, which causes the application to crash.
This PR configures postgres when the helm template command is called.

fix: load image bash postgres config

---

platform-api/src/main/java/io/datacater/core/deployment/StaticConfig.java

When working on #164, I stumbled upon two default values for configuration options that seem to be outdated. This PR fixes this and updates them.

Adjust default values of Deployment Config

---

ui/src/containers/streams/EditStream.js
ui/src/containers/streams/NewStream.js

Our control plane uses the following default values when creating Apache Kafka topics:
- num.partitions = 3
- replication.factor = 1
This commit aligns the default values displayed in the frontend with the ones that are actually used in the control plane.

fix(ui/streams): Align default topic config

---

platform-api/src/main/java/io/datacater/core/config/ConfigUtilities.java
platform-api/src/main/java/io/datacater/core/deployment/DeploymentEndpoint.java
platform-api/src/main/java/io/datacater/core/deployment/DeploymentEntity.java
platform-api/src/main/java/io/datacater/core/deployment/DeploymentSpec.java
platform-api/src/main/java/io/datacater/core/deployment/K8Deployment.java
platform-api/src/main/java/io/datacater/core/stream/StreamEndpoint.java
platform-api/src/main/java/io/datacater/core/stream/StreamsUtilities.java
platform-api/src/test/java/io/datacater/core/deployment/K8DeploymentTest.java

This PR is to fix some bugs regarding the config mapping to streams in seperate places throughout the application

Fix: stream config mapping

---

ui/src/actions/deployments.js
ui/src/components/deployments/ReplicaSelect.js
ui/src/containers/deployments/DeploymentLogs.js
ui/src/containers/deployments/ShowDeployment.js

We support running deployments with multiple replicas.
This commit adds support for selecting a specific replica when viewing a deployment.
The UI shows the health/metrics/logs of the selected replica.
By default, replica 1 is selected.
This PR does not break any existing behavior. At the moment, the UI does not specify the replica when calling the backend, thus it always shows information from the [default replica](https://github.com/DataCater/datacater/blob/main/platform-api/src/main/java/io/datacater/core/deployment/DeploymentEndpoint.java#L69) 1.
Choosing a replica when viewing a deployment:
Choosing a replica when viewing the logs of a deployment:

feat(ui/deployments): Allow selecting a deployment replica

---

gradle.properties

This PR is to upgrade quarkus to the most recent version. Ticket #177 needs at least quarkus 2.16.5.FINAL

build: update Quarkus to most recent version

---

ui/src/components/configs/Tabs.js
ui/src/containers/configs/EditConfig.js
ui/src/containers/configs/NewConfig.js

A couple of places used `class` instead `className` for react components or html tags. This fixes visible bugs from the console.

fix: class to classNames

---

platform-api/src/test/java/io/datacater/core/stream/StreamInspectAvroTest.java
platform-api/src/test/java/io/datacater/core/stream/StreamInspectJsonTest.java
platform-api/src/test/java/io/datacater/core/stream/StreamInspectLongTest.java
platform-api/src/test/java/io/datacater/core/stream/StreamInspectStringTest.java

This PR is to fix some tests that *sometimes* fail.
Before:
- We would send records to kafka (redpanda)
- We would wait unteil the last record has been acked to proceed with th tests
- If the last record took longer than our timeout, the test would fail
Now:
- We have remove the timeout to wait for the last record
- We now use `thread.sleep()` to wait so that most, is not all, records have been sent.
- This should solve the problem of the sporadically failing tests.

fix: change timeout in tests

---

pipeline/src/main/resources/application.yml

The deployment logs look much better nowadays and I had to clean up only one warning to fix #62.
This PR cleans up the deployment logs by removing the Quarkus configuration option `quarkus.container-image.http.cors` that is no longer available and would cause the following warning in the logs:
```
io.quarkus.config Unrecognized configuration key "quarkus.container-image.http.cors" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
```
Fixes #62

Remove obsolete CORS configuration to clean up deployment logs

---

python-runner/requirements.txt

Dependabot [reported](https://github.com/DataCater/datacater/security/dependabot/15) an unintended leak of the `Proxy-Authorization` header in the version of the `requests` library that we are using (all versions < 2.31.0 are affected).
This commit updates the `python_runner/requirements.txt` and requires a version of `requests` where this issue has been fixed (>= 2.31.0).

fix(python-runner): Update requests to >= 2.31.0

---

ui/src/containers/deployments/DeploymentLogs.js
ui/src/reducers/deployments.js

By default, the `/deployments/:uuid/logs` endpoint returns log messages of the given deployment in the JSON-NL format.
In rare cases, this endpoint mixes lines with pure text, i.e., invalid JSON, into the result, which breaks the UI.
Here is an example of such an API response (the first two lines cause the troubles):
```json
[
"Starting the Java application using /opt/jboss/container/java/run/run-java.sh ...",
"INFO exec  java -Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:+ExitOnOutOfMemoryError -cp \".\" -jar /deployments/quarkus-run.jar ",
"{\"timestamp\":\"2023-05-26T06:59:07.497Z\",\"sequence\":71,\"loggerClassName\":\"org.jb …
```

fix(ui/logs): Handle unparseable log messages

---

platform-api/src/main/java/io/datacater/core/deployment/DeploymentEndpoint.java
platform-api/src/main/java/io/datacater/core/deployment/DeploymentUtilities.java
platform-api/src/main/java/io/datacater/core/deployment/K8Deployment.java

Introduce the query parameter `tailingLines` to the `/deployments/:uuid/logs` endpoint, which is set to `100` by default and allows users to define the number of tailing log lines that shall be returned by the API endpoint.
⚠️  **Please note** that this commit slightly changes the default behavior of the endpoint, which did not limit the number of returned log lines in the past, potentially causing issues on both the client and server side.
Unfortunately, I could not test this change, as the mocked Kubernetes server does not return container logs. cc @ChrisRousey @HknLof Can you confirm this observation or are you able to prove me wrong? I would prefer the latter, so we could add tests :)
Fixes #46

feat(deployments/logs): Support defining tailingLines

---

platform-api/src/main/java/io/datacater/core/pipeline/PipelineEndpoint.java

After refactoring our pipelines resource, we were injecting the `PythonRunnerPool` inside the utilities class and trying to access it in the `PipelineEndpoint` through the injected `PipelineUtilities`.
This Fix removes this detour and injects the `PythonRunnerPool` directly in the `PipelineEndpoint` class.

fix: fix injection bug introduced after refactoring pipelines

---

platform-api/src/main/java/io/datacater/core/deployment/DeploymentEndpoint.java
platform-api/src/main/java/io/datacater/core/exceptions/UnhealthyDeploymentException.java
platform-api/src/main/java/io/datacater/core/exceptions/UnhealthyDeploymentExceptionMapper.java

The `/api/v1/deployments/{uuid}/health` endpoint returns the health status of the underlying Kubernetes Deployment.
So far, the endpoint returns the health information in the response body and always uses the HTTP status code 200 (OK) for the response. This is suboptimal and does not allow for a straightforward integration of the endpoint with observability and monitoring products, which often inspect the response status code (and not the response body) for evaluating whether a service is healthy.
This commit changes the behavior of the endpoint as follows:
* If the Kubernetes Deployment is healthy, it returns the HTTP status OK (200).
* If the Kubernetes Deployment is not healthy, it returns the HTTP status INTERNAL SERVER ERROR (500).

feat(api/deployments): Forward health response status
