DataCater/datacater

platform-api/src/main/java/io/datacater/core/DataCater.java
platform-api/src/main/java/io/datacater/core/authentication/AuthenticationEndpoint.java
platform-api/src/main/java/io/datacater/core/deployment/DeploymentEndpoint.java
platform-api/src/main/java/io/datacater/core/filter/FilterEndpoint.java
platform-api/src/main/java/io/datacater/core/pipeline/PipelineEndpoint.java
platform-api/src/main/java/io/datacater/core/stream/StreamEndpoint.java
platform-api/src/main/java/io/datacater/core/transform/TransformEndpoint.java

This commit intoduces OpenAPI annotations to our endpoints as documentation on how to authenticate with our API.

chore(docs): Documentation API authorization

---

platform-api/src/main/java/io/datacater/core/authentication/AuthenticationEndpoint.java
platform-api/src/main/java/io/datacater/core/deployment/DeploymentEndpoint.java
platform-api/src/main/java/io/datacater/core/filter/FilterEndpoint.java
platform-api/src/main/java/io/datacater/core/pipeline/PipelineEndpoint.java
platform-api/src/main/java/io/datacater/core/stream/StreamEndpoint.java
platform-api/src/main/java/io/datacater/core/transform/TransformEndpoint.java
platform-api/src/main/resources/application.yml
platform-api/src/test/java/io/datacater/core/deployment/DatacaterDeploymentEndpointTest.java

This PR updates the endpoint pathing to dynamically change when the version is updated.

dynamic api path

---

ui/package.json
ui/src/containers/streams/EditStream.js
ui/src/containers/streams/NewStream.js
ui/src/helpers/getDeserializerOptions.js
ui/src/helpers/getSerializerOptions.js
ui/src/helpers/getStreamConnectionOptions.js
ui/src/helpers/getStreamTopicOptions.js
ui/src/helpers/isStreamHoldingAvroFormat.js

I improved the user experience and accessibility of the Streams form in the UI, making adding new or editing existing streams more straightforward. The changes incorporate feedback from a UX session with @ChrisRousey.
I recorded the usage of the new form, so you can get an impression of what it feels like:
[![Demo Streams UI](https://cdn.loom.com/sessions/thumbnails/d67de71e573742bb82465eb17903f665-with-play.gif)](https://www.loom.com/share/d67de71e573742bb82465eb17903f665)
Looking forward to your feedback! :)

feat(ui): Improve the accessibility of Streams

---

CONTRIBUTING.md
k8s-manifests/minikube-with-postgres-ns-default.yaml
load-image-k8s.bash
platform-api/src/main/java/io/datacater/core/kubernetes/LabeledStatefulSet.java
platform-api/src/main/java/io/datacater/core/kubernetes/PythonRunnerPool.java

Could not thoroughly test yet, once done will be converted to PR from draft.

Resets pooling correctly. 

---

ui/package-lock.json
ui/package.json
ui/src/actions/deployments.js
ui/src/components/layout/ApiCall.js
ui/src/components/layout/Header.js
ui/src/containers/deployments/ShowDeployment.js
ui/src/reducers/deployments.js
ui/src/scss/main.scss

This PR makes the information from the new `/api/alpha/deployments/{uuid}/health` and `/api/alpha/deployments/{uuid}/metrics` endpoints available in the UI under `/deployments/{uuid}`.

Add health and metrics of deployments to UI

---

helm-charts/datacater/templates/_helpers.tpl
helm-charts/datacater/templates/ui-service.yaml
helm-charts/datacater/templates/ui.yaml
helm-charts/datacater/values.yaml
ui/nginx-config

This change introduces an ui service, deployment, and
changes to the nginx conf. With this change we are
going towards the ability of installation in any namespaces.
Refs:
- https://github.com/DataCater/datacater/issues/76

feat(nginx): user service name for proxy pass

---

.github/workflows/build-test.yaml

For the most recent commit in the `main` branch, provide images with the tag `latest`.

feat(ci): Build latest images for main branch

---

platform-api/src/main/java/io/datacater/core/deployment/StaticConfig.java
platform-api/src/main/resources/application.yml

this PR makes resource limits and requests for deployments configurable and lowers our default value.
refs: #20, #15

feat(deployment): make resources configurable

---

platform-api/src/main/java/io/datacater/core/deployment/DeploymentEndpoint.java
ui/src/reducers/deployments.js

fix(logs): split logs on the api side instead of frontend

---

platform-api/src/main/java/io/datacater/core/stream/KafkaStreamsAdmin.java
serde/src/main/java/io/datacater/core/serde/JsonDeserializer.java
serde/src/main/java/io/datacater/core/serde/JsonSerializer.java

This PR fixes 2 bugs:
- SerDe errors when key or value are null
- Stream not using the partitions from as defined

fix: minor fixes to Streams and SerDe

---

helm-charts/datacater/values.yaml

@flippingbits @ChrisRousey Found some errors on a fresh install. Once, tested with new feature, I will update the `minikube-any-namespace.yaml`.

fix(helm): introduce some defaults for db connections and fix python-runner reference

---

.github/workflows/build-test.yaml

`github.base_ref` references the target branch.
Also try to get rid of minikube for now.
Refs:
- https://docs.github.com/en/actions/learn-github-actions/contexts#github-context

feat(ci): build-images and push, once there is a PR into main

---

helm-charts/datacater/Chart.yaml
helm-charts/datacater/values.yaml
k8s-manifests/minikube-any-namespace.yaml
k8s-manifests/minikube-with-postgres-and-redpanda.yaml
k8s-manifests/minikube-with-postgres-ns-default.yaml

Update the Helm chart and Kubernetes manifests to the latest pre-release version.

feat(helm): Upgrade to f27eff

---

README.md

I added a [demo video of our 2023.1 release](https://www.loom.com/share/15947f13e71540948e3f9d57eac64976) to the readme. It took me a couple of tries, so please squash the commits when merging. :)

Add demo video to readme

---

python-runner/README.md
python-runner/build.sh

Update the readme of the Python runner and describe how to execute the tests. Remove an obsolete build script from the Python runner folder.

Update readme of Python runner

---

platform-api/src/main/java/io/datacater/core/config/ConfigUtilities.java
platform-api/src/main/java/io/datacater/core/stream/KafkaStreamsAdmin.java
platform-api/src/main/java/io/datacater/core/utilities/JsonUtilities.java
ui/src/actions/configs.js
ui/src/components/configs/Tabs.js
ui/src/components/layout/Navigation.js
ui/src/containers/DataCaterApp.js
ui/src/containers/configs/EditConfig.js
ui/src/containers/configs/ListConfigs.js
ui/src/containers/configs/NewConfig.js
ui/src/containers/configs/ShowConfig.js
ui/src/containers/deployments/EditDeployment.js
ui/src/containers/deployments/NewDeployment.js
ui/src/containers/streams/EditStream.js
ui/src/containers/streams/NewStream.js
ui/src/helpers/getConfigKindOptions.js
ui/src/reducers/configs.js
ui/src/reducers/index.js

Add the config functionality to the frontend
work in progress

feat(UI): Add config functionality

---

ui/src/containers/configs/EditConfig.js
ui/src/containers/configs/NewConfig.js
ui/src/containers/deployments/EditDeployment.js
ui/src/containers/deployments/NewDeployment.js

This PR introduced the replicas configuration to our frontend newDeployment, editDeployment, newConfig and editConfig resources,

feature(ui): add deployment replicas to frontend

---

k8s-manifests/minikube-with-postgres-and-redpanda.yaml
platform-api/src/main/java/io/datacater/core/deployment/StaticConfig.java
platform-api/src/main/resources/application.yml

Update the application version to `2023.2` at locations that still reference to the prior release (`2023.1`).

fix(platform-api): Update application version

---

.github/workflows/build-test.yaml
platform-api/src/main/java/io/datacater/core/info/ContactInfo.java
platform-api/src/main/java/io/datacater/core/info/Info.java
platform-api/src/main/java/io/datacater/core/info/InfoEndpoint.java
platform-api/src/main/java/io/datacater/core/info/ResourceInfo.java
platform-api/src/main/java/io/datacater/core/info/ResourceItem.java
platform-api/src/main/java/io/datacater/core/info/StaticInformation.java
platform-api/src/main/java/io/datacater/core/info/VersionInfo.java
platform-api/src/test/java/io/datacater/core/info/InfoEndpointTest.java

This PR is for the implementiation of a root information endpoint as explained in ticket #205

feature: create root info endpoint

---

platform-api/src/main/java/io/datacater/core/stream/StreamEndpoint.java
platform-api/src/test/java/io/datacater/core/stream/StreamInspectAvroTest.java

with PR #210 support yaml payloads, the security annotations were removed for testing purposes and never re-added

fix: re-add security annotations for streams

---

ui/src/components/configs/Tabs.js
ui/src/components/layout/ApiCall.js
ui/src/components/layout/Header.js
ui/src/components/pipelines/pipeline_designer/context_bar/DebugView.js
ui/src/components/pipelines/pipeline_designer/context_bar/Field.js
ui/src/components/pipelines/pipeline_designer/context_bar/Record.js
ui/src/components/pipelines/pipeline_designer/grid/StepsList.js
ui/src/containers/configs/EditConfig.js
ui/src/containers/configs/NewConfig.js
ui/src/containers/deployments/EditDeployment.js
ui/src/containers/deployments/NewDeployment.js
ui/src/containers/pipelines/NewPipeline.js
ui/src/containers/streams/EditStream.js
ui/src/containers/streams/NewStream.js

This PR changes incorrectly used <a>-elements in the frontend to button elements.

UI: remove incorrect <a> tags

---

.github/workflows/build-test.yaml

Run `npx prettier` in the CI pipeline to verify the correct formatting of our JavaScript code (located under `/ui/src`).
Fixes #228

feat(ci): Verify formatting of JavaScript code

---

CONTRIBUTING.md
platform-api/src/main/java/io/datacater/core/deployment/K8Deployment.java
platform-api/src/main/java/io/datacater/core/deployment/StaticConfig.java
platform-api/src/main/java/io/datacater/core/kubernetes/DataCaterK8sConfig.java
platform-api/src/main/java/io/datacater/core/kubernetes/PythonRunnerPool.java
platform-api/src/main/java/io/datacater/core/lifecycle/FiltersRepository.java
platform-api/src/main/java/io/datacater/core/lifecycle/StaticConfig.java
platform-api/src/main/java/io/datacater/core/lifecycle/TransformsRepository.java
platform-api/src/main/java/io/datacater/core/pipeline/PipelineUtilities.java
platform-api/src/main/java/io/datacater/core/pipeline/StaticConfig.java
platform-api/src/main/java/io/datacater/core/stream/KafkaStreamsAdmin.java
platform-api/src/main/java/io/datacater/core/stream/StaticConfig.java

This PR aims to create a common understanding and guideline on when and where to log application information.
This should provide a better user and developer experience for anyone using DataCater.
Please give me feedback on the guidelines i have added and feel free to suggest changes or anything that should be added to the guidelines.
refs: #190

docs: create logging guidelines
